CREATE DATABASE[Corporate]
GO
USE[Corporate]
GO
CREATE TABLE[Role](
[ID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL
);
GO
CREATE TABLE[Company](
[ID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,
[Telephone] INT NOT NULL,
[Adress] NVARCHAR(50) NOT NULL,
);
GO
CREATE TABLE[Person](
[ID] INT PRIMARY KEY IDENTITY,
[FirstName] NVARCHAR(50) NOT NULL,
[LastName] NVARCHAR(50) NOT NULL,
[MidleName] NVARCHAR(50) ,
[Telephone] INT NOT NULL,
[E-Mail] NVARCHAR(50) NOT NULL,
[RoleID] INT FOREIGN KEY REFERENCES[Role](ID) NOT NULL,
[Adress] NVARCHAR(50),
[PussNumber] INT,
[Price] INT,
[CompanyID] INT FOREIGN KEY REFERENCES[Company](ID),
);
GO
CREATE TABLE[Place](
[ID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,
[Adress] NVARCHAR(50) NOT NULL,
[Telephone] INT NOT NULL,
[Square] INT NOT NULL,
[MaxPersone] INT NOT NULL
);
GO
CREATE TABLE[Order](
[ID] INT PRIMARY KEY IDENTITY,
[OrganizerID] INT FOREIGN KEY REFERENCES[Person](ID) NOT NULL,
[ClientID] INT FOREIGN KEY REFERENCES[Person](ID) NOT NULL,
[PlaceID] INT FOREIGN KEY REFERENCES[Place](ID) NOT NULL,
[CountPerson] INT NOT NULL,
[Date] DATETIME NOT NULL
);
GO
CREATE TABLE[Stars](
[StarID] INT FOREIGN KEY REFERENCES[Person](ID) NOT NULL,
[OrderID] INT FOREIGN KEY REFERENCES[Order](ID) NOT NULL
);
GO
CREATE TABLE[Author](
[ID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL
);
GO
CREATE TABLE[Music](
[ID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,
[AuthorID] INT FOREIGN KEY REFERENCES[Author](ID)
);
GO
CREATE TABLE[MusicOperate](
[MusicID]INT FOREIGN KEY REFERENCES[Music](ID) NOT NULL,
[OrderID]INT FOREIGN KEY REFERENCES[Order](ID) NOT NULL
);
GO
CREATE TABLE[Product](
[ID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,
[Unit] NVARCHAR(30) NOT NULL,
[Count] INT NOT NULL,
[Description] NVARCHAR(MAX) NOT NULL
);
GO
CREATE TABLE[Invoices](
[ID]INT PRIMARY KEY IDENTITY,
[ProductID]INT FOREIGN KEY REFERENCES[Product](ID) NOT NULL,
[Count]INT NOT NULL
);
GO
CREATE TABLE[ProductOperate](
[InvoicesID]INT FOREIGN KEY REFERENCES[Invoices](ID) NOT NULL,
[OrderID]INT FOREIGN KEY REFERENCES[Order](ID) NOT NULL
);
